# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Cidade.create! nome: 'Manaus - AM'
Cidade.create! nome: 'Belém - PA'
Cidade.create! nome: 'Boa Vista - RR'
Cidade.create! nome: 'Porto Velho - RR'
Cidade.create! nome: 'Rio Branco - AC'
Cidade.create! nome: 'Macapá - AP'
Cidade.create! nome: 'Iranduba - AM'
Cidade.create! nome: 'Manacapuru - AM'
Cidade.create! nome: 'Novo Airão - AM'
Cidade.create! nome: 'Coari - AM'
Cidade.create! nome: 'Parintins - AM'
Cidade.create! nome: 'Tabatinga- AM'
Cidade.create! nome: 'Tefé - AM'
Cidade.create! nome: 'Humaitá - AM'
Cidade.create! nome: 'Barcelos - AM'
Cidade.create! nome: 'Santarém - PA'
Cidade.create! nome: 'Cruzeiro do Sul - AC'
Cidade.create! nome: 'Assis Brasil - AC'
Cidade.create! nome: 'Auaris - RR'
Cidade.create! nome: 'Barcelos'
Cidade.create! nome: 'Bonfim - RR'
Cidade.create! nome: 'Cucuí - AM'
Cidade.create! nome: 'Epitacolandia - AC'
Cidade.create! nome: 'Estirão do Equador - AM'
Cidade.create! nome: 'Guajará Mirim - RO'
Cidade.create! nome: 'Ipiranga - AM'
Cidade.create! nome: 'Maturacá - AM'
Cidade.create! nome: 'Marechal Thaumaturgo - AC'
Cidade.create! nome: 'Manicoré - AM'
Cidade.create! nome: 'Normandia - RR'
Cidade.create! nome: 'Pacaraima - RR'
Cidade.create! nome: 'Palmeira do Javari - AM'
Cidade.create! nome: 'Pari-cachoera - AM'
Cidade.create! nome: 'Plácido de Castro - AC'
Cidade.create! nome: 'Principe da Beira - RO'
Cidade.create! nome: 'Querari - AM'
Cidade.create! nome: 'Santa Rosa da Cachoeira - AM'
Cidade.create! nome: 'São joaquim - AM'
Cidade.create! nome: 'São Salvador - AC'
Cidade.create! nome: 'Surucucu - RR'
Cidade.create! nome: 'Tunuí - AM'
Cidade.create! nome: 'Uiramutã - RR'
Cidade.create! nome: 'Vila Bitencourt - AM'
Cidade.create! nome: 'Vilhena - RO'
Cidade.create! nome: 'Yauaretê - AM'
Cidade.create! nome: 'Maturacá - AM'

Quartel.create! nome: '4º CTA'
Quartel.create! nome: 'Cmdo CMA'
Quartel.create! nome: '12ª RM'
Quartel.create! nome: '1ª Bda Inf Sl'
Quartel.create! nome: '2ª Bda Inf Sl'
Quartel.create! nome: '16ª Bda Inf Sl'
Quartel.create! nome: '17ª Bda Inf Sl'
Quartel.create! nome: '2º GEC'
Quartel.create! nome: 'HMAM'
Quartel.create! nome: 'HGuT'
Quartel.create! nome: 'HGuPV'
Quartel.create! nome: 'CRO/12'
Quartel.create! nome: 'CF RR/7º BIS'
Quartel.create! nome: '1º BIS(Amv)'
Quartel.create! nome: 'CF Sol/8º BIS'
Quartel.create! nome: '61º BIS'
Quartel.create! nome: 'CF AC/4º BIS'
Quartel.create! nome: 'Cmdo Fron RO/6º BIS'
Quartel.create! nome: '17ª BaLog'
Quartel.create! nome: '5º BECnst'
Quartel.create! nome: '6º BECnst'
Quartel.create! nome: '7º BECnst'
Quartel.create! nome: '8º BECnst'
Quartel.create! nome: '4ª CGeo'
Quartel.create! nome: '7º BECnst'
Quartel.create! nome: '12ª ICFEx'
Quartel.create! nome: '3ª CiaFEsp'
Quartel.create! nome: '61º BIS'
Quartel.create! nome: '29ª CSM'
Quartel.create! nome: '31ª CSM'
Quartel.create! nome: 'CIGS'
Quartel.create! nome: '4º BAvEx'
Quartel.create! nome: '1ª BComSl'
Quartel.create! nome: '12º BSup'
Quartel.create! nome: 'PqRMnt/12'
Quartel.create! nome: 'CECMA'
Quartel.create! nome: 'HGuSGC'
Quartel.create! nome: '10º GAC Sl'
Quartel.create! nome: '1ª BaLog'
Quartel.create! nome: '3º BIS'
Quartel.create! nome: '16ª BaLog'
Quartel.create! nome: '54º BIS'
Quartel.create! nome: '17° BIS'
Quartel.create! nome: '7º BPE'
Quartel.create! nome: 'CEF/4º BIS'
Quartel.create! nome: '5º BIS'
Quartel.create! nome: 'CMM'
Quartel.create! nome: '4ª Cia Intlg'
Quartel.create! nome: 'Cia C 12ªRM'
Quartel.create! nome: 'Cia C 1ª Bda Inf Sl'
Quartel.create! nome: '12º Esq C Mec'
Quartel.create! nome: '1º Pel Com Sl'
Quartel.create! nome: '32º Pel PE'
Quartel.create! nome: 'Cia C 2ª Bda Inf Sl'
Quartel.create! nome: '22º Pel PE'
Quartel.create! nome: '2º Pel Com Sl'
Quartel.create! nome: 'Cia C 16ª Bda Inf Sl'
Quartel.create! nome: '16º Pel Com Sl'
Quartel.create! nome: '34º Pel PE'
Quartel.create! nome: 'Cia C 17ª Bda Inf Sl'
Quartel.create! nome: '17º Pel Com Sl'
Quartel.create! nome: '17º Pel PE'
Quartel.create! nome: '21ª Cia E Cnst'
Quartel.create! nome: '17º Cia Inf Sl'
Quartel.create! nome: 'Cia Cmdo CMA'
Quartel.create! nome: '1º PEF / 7° BIS'
Quartel.create! nome: '2º PEF / 7° BIS'
Quartel.create! nome: '3º PEF / 7° BIS'
Quartel.create! nome: '4º PEF / 7° BIS'
Quartel.create! nome: '5º PEF / 7° BIS'
Quartel.create! nome: '6º PEF / 7° BIS'
Quartel.create! nome: '1º PEF / 5° BIS'
Quartel.create! nome: '2º PEF / 5° BIS'
Quartel.create! nome: '3º PEF / 5° BIS'
Quartel.create! nome: '4º PEF / 5° BIS'
Quartel.create! nome: '5º PEF / 5° BIS'
Quartel.create! nome: '6º PEF / 5° BIS'
Quartel.create! nome: '7º PEF / 5° BIS'
Quartel.create! nome: '1º PEF / 8° BIS'
Quartel.create! nome: '2º PEF / 8° BIS'
Quartel.create! nome: '3º PEF / 8° BIS'
Quartel.create! nome: '4º PEF / 8° BIS'
Quartel.create! nome: '1° DEF / 61° BIS'
Quartel.create! nome: '2° DEF / 61° BIS'
Quartel.create! nome: '1º PEF / 6° BIS'
Quartel.create! nome: 'CEF / 4° BIS'
Quartel.create! nome: '2º PEF / 4° BIS'
Quartel.create! nome: '3º PEF / 4° BIS'
Quartel.create! nome: '4º PEF / 4° BIS'

Idioma.create! lingua_nivel: 'Inglês: lê bem'
Idioma.create! lingua_nivel: 'Inglês: lê bem, ouve bem'
Idioma.create! lingua_nivel: 'Inglês: lê bem, ouve bem, fala bem'
Idioma.create! lingua_nivel: 'Inglês: lê bem, ouve bem, fala bem, escreve bem'
Idioma.create! lingua_nivel: 'Espanhol: lê bem'
Idioma.create! lingua_nivel: 'Espanhol: lê bem, ouve bem'
Idioma.create! lingua_nivel: 'Espanhol: lê bem, ouve bem, fala bem'
Idioma.create! lingua_nivel: 'Espanhol: lê bem, ouve bem, fala bem, escreve bem'

Formmilitar.create! titulo: 'Instrução Básica e/ou Qualificação'
Formmilitar.create! titulo: 'Curso de Formação de Cabos'
Formmilitar.create! titulo: 'STT - Administração'
Formmilitar.create! titulo: 'STT - TI'
Formmilitar.create! titulo: 'Sgt Tmp Combatente'
Formmilitar.create! titulo: 'Sgt Tmp Logística'
Formmilitar.create! titulo: 'Sgt Tmp Saúde'
Formmilitar.create! titulo: 'OTT - Administração'
Formmilitar.create! titulo: 'OTT - TI'
Formmilitar.create! titulo: 'OTT - Direito'
Formmilitar.create! titulo: 'Of Tmp Saúde'
Formmilitar.create! titulo: 'Of Tmp Combatente'
Formmilitar.create! titulo: 'Of Tmp Logística'

Areaatuacao.create! titulo: 'Transportes e logística'
Areaatuacao.create! titulo: 'Serviços empresariais'
Areaatuacao.create! titulo: 'Viagem, lazer e turismo'
Areaatuacao.create! titulo: 'Contabilidade e consultoria'
Areaatuacao.create! titulo: 'Tecnologia da Informação'
Areaatuacao.create! titulo: 'Saúde'
Areaatuacao.create! titulo: 'Atacado'
Areaatuacao.create! titulo: 'Bares e restaurantes'
Areaatuacao.create! titulo: 'Construção civil'
Areaatuacao.create! titulo: 'Engenharia'
Areaatuacao.create! titulo: 'Administração pública'
Areaatuacao.create! titulo: 'Segurança pública e privada'
Areaatuacao.create! titulo: 'Educação'
Areaatuacao.create! titulo: 'Gestão empresarial'
Areaatuacao.create! titulo: 'Indústria'
Areaatuacao.create! titulo: 'Varejo'
Areaatuacao.create! titulo: 'Mídia e comunicação'
Areaatuacao.create! titulo: 'Telecomunicações'
Areaatuacao.create! titulo: 'Manutenção Mecânica'

Habilidade.create! titulo: 'Mecânica de automóvel'
Habilidade.create! titulo: 'Eletricista'
Habilidade.create! titulo: 'Carpinteiro'
Habilidade.create! titulo: 'Encanador'
Habilidade.create! titulo: 'Desenvolvimento de software'
Habilidade.create! titulo: 'Cozinheiro'
Habilidade.create! titulo: 'Marceneiro'
Habilidade.create! titulo: 'Instalador de ar condicionado'
Habilidade.create! titulo: 'Mecânico de ar condicionado'
Habilidade.create! titulo: 'Pintor'
Habilidade.create! titulo: 'Pedreiro'
Habilidade.create! titulo: 'Manutenção de computadores'
Habilidade.create! titulo: 'Mestre de obras'
Habilidade.create! titulo: 'Segurança de eventos'
Habilidade.create! titulo: 'CNH C'
Habilidade.create! titulo: 'CNH D'
Habilidade.create! titulo: 'CNH E'
Habilidade.create! titulo: 'Serviços gerais'
Habilidade.create! titulo: 'Lanternagem'
Habilidade.create! titulo: 'Condutor de embarcações'
Habilidade.create! titulo: 'AutoCAD'
Habilidade.create! titulo: 'Padeiro'
Habilidade.create! titulo: 'Confeiteiro'
Habilidade.create! titulo: 'Costureiro'
Habilidade.create! titulo: 'Soldador'
Habilidade.create! titulo: 'Instalador de câmeras e alarmes'
Habilidade.create! titulo: ''
