# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cidade.create! nome: 'Manaus - AM'
Cidade.create! nome: 'Belém - PA'
Cidade.create! nome: 'Boa Vista - RR'
Cidade.create! nome: 'Porto Velho - RR'
Cidade.create! nome: 'Rio Branco - AC'
Cidade.create! nome: 'Macapá - AP'
Cidade.create! nome: 'Iranduba - AM'
Cidade.create! nome: 'Manacapuru - AM'
Cidade.create! nome: 'Novo Airão - AM'
Cidade.create! nome: 'Coari - AM'
Cidade.create! nome: 'Parintins - AM'
Cidade.create! nome: 'Tabatinga- AM'
Cidade.create! nome: 'Tefé - AM'
Cidade.create! nome: 'Humaitá - AM'
Cidade.create! nome: 'Barcelos - AM'
Cidade.create! nome: 'Santarém - PA'
Cidade.create! nome: 'Cruzeiro do Sul - AC'
Cidade.create! nome: 'Assis Brasil - AC'
Cidade.create! nome: 'Auaris - RR'
Cidade.create! nome: 'Barcelos'
Cidade.create! nome: 'Bonfim - RR'
Cidade.create! nome: 'Cucuí - AM'
Cidade.create! nome: 'Epitacolandia - AC'
Cidade.create! nome: 'Estirão do Equador - AM'
Cidade.create! nome: 'Guajará Mirim - RO'
Cidade.create! nome: 'Ipiranga - AM'
Cidade.create! nome: 'Maturacá - AM'
Cidade.create! nome: 'Marechal Thaumaturgo - AC'
Cidade.create! nome: 'Manicoré - AM'
Cidade.create! nome: 'Normandia - RR'
Cidade.create! nome: 'Pacaraima - RR'
Cidade.create! nome: 'Palmeira do Javari - AM'
Cidade.create! nome: 'Pari-cachoera - AM'
Cidade.create! nome: 'Plácido de Castro - AC'
Cidade.create! nome: 'Principe da Beira - RO'
Cidade.create! nome: 'Querari - AM'
Cidade.create! nome: 'Santa Rosa da Cachoeira - AM'
Cidade.create! nome: 'São joaquim - AM'
Cidade.create! nome: 'São Salvador - AC'
Cidade.create! nome: 'Surucucu - RR'
Cidade.create! nome: 'Tunuí - AM'
Cidade.create! nome: 'Uiramutã - RR'
Cidade.create! nome: 'Vila Bitencourt - AM'
Cidade.create! nome: 'Vilhena - RO'
Cidade.create! nome: 'Yauaretê - AM'
Cidade.create! nome: 'Maturacá - AM'

Quartel.create! nome: '4º CTA'
Quartel.create! nome: 'Cmdo CMA'
Quartel.create! nome: '12ª RM'
Quartel.create! nome: '1ª Bda Inf Sl'
Quartel.create! nome: '2ª Bda Inf Sl'
Quartel.create! nome: '16ª Bda Inf Sl'
Quartel.create! nome: '17ª Bda Inf Sl'
Quartel.create! nome: '2º GEC'
Quartel.create! nome: 'HMAM'
Quartel.create! nome: 'HGuT'
Quartel.create! nome: 'HGuPV'
Quartel.create! nome: 'CRO/12'
Quartel.create! nome: 'CFAC/4º BIS'
Quartel.create! nome: 'CFRN/5º BIS'
Quartel.create! nome: 'CFRO/6º BIS'
Quartel.create! nome: 'CF RR/7º BIS'
Quartel.create! nome: 'CFSOL/8º BIS'
Quartel.create! nome: '1º BIS(Amv)'
Quartel.create! nome: '61º BIS'
Quartel.create! nome: '17ª BaLog'
Quartel.create! nome: '5º BECnst'
Quartel.create! nome: '6º BECnst'
Quartel.create! nome: '7º BECnst'
Quartel.create! nome: '8º BECnst'
Quartel.create! nome: '4ª CGeo'
Quartel.create! nome: '7º BECnst'
Quartel.create! nome: '12ª ICFEx'
Quartel.create! nome: '3ª CiaFEsp'
Quartel.create! nome: '61º BIS'
a = Quartel.create! ([{nome: '29ª CSM'}])
Quartel.create! nome: '31ª CSM'
Quartel.create! nome: 'CIGS'
Quartel.create! nome: '4º BAvEx'
Quartel.create! nome: '1ª BComSl'
Quartel.create! nome: '12º BSup'
Quartel.create! nome: 'PqRMnt/12'
Quartel.create! nome: 'CECMA'
Quartel.create! nome: 'HGuSGC'
Quartel.create! nome: '10º GAC Sl'
Quartel.create! nome: '1ª BaLog'
Quartel.create! nome: '3º BIS'
Quartel.create! nome: '16ª BaLog'
Quartel.create! nome: '54º BIS'
Quartel.create! nome: '17° BIS'
Quartel.create! nome: '7º BPE'
Quartel.create! nome: 'CEF/4º BIS'
Quartel.create! nome: '5º BIS'
Quartel.create! nome: 'CMM'
Quartel.create! nome: '4ª Cia Intlg'
Quartel.create! nome: 'Cia C 12ªRM'
Quartel.create! nome: 'Cia C 1ª Bda Inf Sl'
Quartel.create! nome: '12º Esq C Mec'
Quartel.create! nome: '1º Pel Com Sl'
Quartel.create! nome: '32º Pel PE'
Quartel.create! nome: 'Cia C 2ª Bda Inf Sl'
Quartel.create! nome: '22º Pel PE'
Quartel.create! nome: '2º Pel Com Sl'
Quartel.create! nome: 'Cia C 16ª Bda Inf Sl'
Quartel.create! nome: '16º Pel Com Sl'
Quartel.create! nome: '34º Pel PE'
Quartel.create! nome: 'Cia C 17ª Bda Inf Sl'
Quartel.create! nome: '17º Pel Com Sl'
Quartel.create! nome: '17º Pel PE'
Quartel.create! nome: '21ª Cia E Cnst'
Quartel.create! nome: '17º Cia Inf Sl'
Quartel.create! nome: 'Cia Cmdo CMA'
Quartel.create! nome: '1º PEF / 7° BIS'
Quartel.create! nome: '2º PEF / 7° BIS'
Quartel.create! nome: '3º PEF / 7° BIS'
Quartel.create! nome: '4º PEF / 7° BIS'
Quartel.create! nome: '5º PEF / 7° BIS'
Quartel.create! nome: '6º PEF / 7° BIS'
Quartel.create! nome: '1º PEF / 5° BIS'
Quartel.create! nome: '2º PEF / 5° BIS'
Quartel.create! nome: '3º PEF / 5° BIS'
Quartel.create! nome: '4º PEF / 5° BIS'
Quartel.create! nome: '5º PEF / 5° BIS'
Quartel.create! nome: '6º PEF / 5° BIS'
Quartel.create! nome: '7º PEF / 5° BIS'
Quartel.create! nome: '1º PEF / 8° BIS'
Quartel.create! nome: '2º PEF / 8° BIS'
Quartel.create! nome: '3º PEF / 8° BIS'
Quartel.create! nome: '4º PEF / 8° BIS'
Quartel.create! nome: '1° DEF / 61° BIS'
Quartel.create! nome: '2° DEF / 61° BIS'
Quartel.create! nome: '1º PEF / 6° BIS'
Quartel.create! nome: 'CEF / 4° BIS'
Quartel.create! nome: '2º PEF / 4° BIS'
Quartel.create! nome: '3º PEF / 4° BIS'
Quartel.create! nome: '4º PEF / 4° BIS'

AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password', quartel: a.first, status: 1, tipo: 0, cpf: '11122233344', nome: 'Admin Teste')

Idioma.create! lingua_nivel: 'Inglês: consegue ler frases básicas, como manuais de instrução'
Idioma.create! lingua_nivel: 'Inglês: consegue ler textos curtos, como em websites'
Idioma.create! lingua_nivel: 'Inglês: consegue ler um livro'
Idioma.create! lingua_nivel: 'Inglês: consegue compreender diálogos simples'
Idioma.create! lingua_nivel: 'Inglês: consegue compreender qualquer diálogo'
Idioma.create! lingua_nivel: 'Inglês: consegue falar frases básicas'
Idioma.create! lingua_nivel: 'Inglês: consegue travar um diálogo'
Idioma.create! lingua_nivel: 'Inglês: consegue escrever frases curtas'
Idioma.create! lingua_nivel: 'Inglês: consegue escrever artigos longos'
Idioma.create! lingua_nivel: 'Espanhol: consegue ler frases básicas, como manuais de instrução'
Idioma.create! lingua_nivel: 'Espanhol: consegue ler textos curtos, como em websites'
Idioma.create! lingua_nivel: 'Espanhol: consegue ler um livro'
Idioma.create! lingua_nivel: 'Espanhol: consegue compreender diálogos simples'
Idioma.create! lingua_nivel: 'Espanhol: consegue compreender qualquer diálogo'
Idioma.create! lingua_nivel: 'Espanhol: consegue falar frases básicas'
Idioma.create! lingua_nivel: 'Espanhol: consegue travar um diálogo'
Idioma.create! lingua_nivel: 'Espanhol: consegue escrever frases curtas'
Idioma.create! lingua_nivel: 'Espanhol: consegue escrever artigos longos'

Formmilitar.create! titulo: 'Instrução Básica e/ou Qualificação de Soldados'
Formmilitar.create! titulo: 'Curso de Formação de Cabos'
Formmilitar.create! titulo: 'Sargento Técnico Temporário - Administração'
Formmilitar.create! titulo: 'Sargento Técnico Temporário - Tecnologia da Informação'
Formmilitar.create! titulo: 'Sargento Temporário Combatente'
Formmilitar.create! titulo: 'Sargento Temporário Logística'
Formmilitar.create! titulo: 'Sargento Temporário Saúde'
Formmilitar.create! titulo: 'Oficial Temporário Administração'
Formmilitar.create! titulo: 'Oficial Temporário Tecnologia da Informação'
Formmilitar.create! titulo: 'Oficial Temporário Direito'
Formmilitar.create! titulo: 'Oficial Temporário Saúde'
Formmilitar.create! titulo: 'Oficial Temporário Combatente'
Formmilitar.create! titulo: 'Oficial Temporário Logística'

Areaatuacao.create! titulo: 'Transportes e logística'
Areaatuacao.create! titulo: 'Serviços empresariais'
Areaatuacao.create! titulo: 'Viagem, lazer e turismo'
Areaatuacao.create! titulo: 'Contabilidade e consultoria'
Areaatuacao.create! titulo: 'Tecnologia da Informação'
Areaatuacao.create! titulo: 'Saúde'
Areaatuacao.create! titulo: 'Atacado'
Areaatuacao.create! titulo: 'Bares e restaurantes'
Areaatuacao.create! titulo: 'Construção civil'
Areaatuacao.create! titulo: 'Engenharia'
Areaatuacao.create! titulo: 'Administração pública'
Areaatuacao.create! titulo: 'Segurança pública e privada'
Areaatuacao.create! titulo: 'Educação'
Areaatuacao.create! titulo: 'Gestão empresarial'
Areaatuacao.create! titulo: 'Indústria'
Areaatuacao.create! titulo: 'Varejo'
Areaatuacao.create! titulo: 'Mídia e comunicação'
Areaatuacao.create! titulo: 'Telecomunicações'
Areaatuacao.create! titulo: 'Manutenção Mecânica'

Habilidade.create! titulo: 'Mecânica de automóvel'
Habilidade.create! titulo: 'Eletricista'
Habilidade.create! titulo: 'Carpinteiro'
Habilidade.create! titulo: 'Encanador'
Habilidade.create! titulo: 'Desenvolvimento de software'
Habilidade.create! titulo: 'Cozinheiro'
Habilidade.create! titulo: 'Marceneiro'
Habilidade.create! titulo: 'Instalador de ar condicionado'
Habilidade.create! titulo: 'Mecânico de ar condicionado'
Habilidade.create! titulo: 'Pintor'
Habilidade.create! titulo: 'Pedreiro'
Habilidade.create! titulo: 'Manutenção de computadores'
Habilidade.create! titulo: 'Mestre de obras'
Habilidade.create! titulo: 'Segurança de eventos'
Habilidade.create! titulo: 'Serviços gerais'
Habilidade.create! titulo: 'Lanternagem'
Habilidade.create! titulo: 'Condutor de embarcações'
Habilidade.create! titulo: 'AutoCAD'
Habilidade.create! titulo: 'Padeiro'
Habilidade.create! titulo: 'Confeiteiro'
Habilidade.create! titulo: 'Costureiro'
Habilidade.create! titulo: 'Soldador'
Habilidade.create! titulo: 'Instalador de câmeras e alarmes'
Habilidade.create! titulo: 'Serralheiro'
Habilidade.create! titulo: 'Metalúrgico'
Habilidade.create! titulo: 'Agricultor'

Atributoafetivo.create! titulo: 'Assiduidade'
Atributoafetivo.create! titulo: 'Pontualidade'
Atributoafetivo.create! titulo: 'Disciplina'
Atributoafetivo.create! titulo: 'Liderança'
Atributoafetivo.create! titulo: 'Apresentação'
Atributoafetivo.create! titulo: 'Dedicação'
Atributoafetivo.create! titulo: 'Iniciativa'
Atributoafetivo.create! titulo: 'Produtividade'
Atributoafetivo.create! titulo: 'Comunicação'
Atributoafetivo.create! titulo: 'Estabilidade Emocional'
Atributoafetivo.create! titulo: 'Resistência Física'

Cnh.create! titulo: 'A'
Cnh.create! titulo: 'B'
Cnh.create! titulo: 'C'
Cnh.create! titulo: 'D'
Cnh.create! titulo: 'E'

Curso.create! titulo: 'Operador de Empilhadeira'
Curso.create! titulo: 'Confeiteiro de Tortas Finas'
Curso.create! titulo: 'Pizzaiolo'
Curso.create! titulo: 'Confeiteiro de Tortas Geladas'
Curso.create! titulo: 'Comandos Elétricos'
Curso.create! titulo: 'Instalação de Sistema de Controle de Acesso'
Curso.create! titulo: 'Instalador Eletroeletrônico'
Curso.create! titulo: 'Instalador Hidráulico Residencial'
Curso.create! titulo: 'Mecânico de Motocicleta'
Curso.create! titulo: 'Mecânico de Motor de Popa'
Curso.create! titulo: 'Operador de Escavadeira'
Curso.create! titulo: 'Operador de Motoniveladora'
Curso.create! titulo: 'Operador de Pá Carregadeira'
Curso.create! titulo: 'Operador de Paleteira Elétrica'
Curso.create! titulo: 'Operador de Ponte Rolante'
Curso.create! titulo: 'Operador de Retroescavadeira'
Curso.create! titulo: 'Operador de Trator de Esteira'
Curso.create! titulo: 'Padeiro'
Curso.create! titulo: 'Pedreiro'
Curso.create! titulo: 'Reparador de Aparelho Condicionador de Ar (janela e split)'
Curso.create! titulo: 'Soldador a Eletrodo Revestido'
Curso.create! titulo: 'Eletricidade Aplicada à Construção Civil'
Curso.create! titulo: 'Operador de Máquinas de Marcenaria'
Curso.create! titulo: 'Assistente Administrativo na Construção Civil'
Curso.create! titulo: 'Eletricista Instalador Predial de Baixa Tensão'
Curso.create! titulo: 'Eletricista Instalador Residencial'
Curso.create! titulo: 'Pintor de Obras'
Curso.create! titulo: 'Instalação de Sistema de Alarme'
Curso.create! titulo: 'Instalação de Sistema de CFTV de Segurança'
Curso.create! titulo: 'Instalador de Sistemas Eletrônicos de Segurança'
Curso.create! titulo: 'NR 35 – Trabalho em Altura'
Curso.create! titulo: 'NR 10 - Trabalho com Eletricidade'
Curso.create! titulo: 'Orçamento de Obras'
Curso.create! titulo: 'Tecnologia da Construção à Seco (Gesso Acartonado)'
Curso.create! titulo: 'Lógica de Programação'
Curso.create! titulo: 'Tecnologia da Informação e Comunicação'
Curso.create! titulo: 'Noções Básicas de Mecânica Automotiva'

Formacaoacad.create! titulo: 'Licenciatura em Educação Física'
Formacaoacad.create! titulo: 'Licenciatura e Bacharelado em Educação Física'
Formacaoacad.create! titulo: 'Bacharelado em Enfermagem'
Formacaoacad.create! titulo: 'Bacharelado em Fisioterapia'
Formacaoacad.create! titulo: 'Bacharelado em Veterinária'
Formacaoacad.create! titulo: 'Bacharelado em Nutrição'
Formacaoacad.create! titulo: 'Bacharelado em Odontologia'
Formacaoacad.create! titulo: 'Bacharelado em Ciência da Computação'
Formacaoacad.create! titulo: 'Bacharelado em Engenharia Civil'
Formacaoacad.create! titulo: 'Bacharelado em Engenharia da Computação'
Formacaoacad.create! titulo: 'Bacharelado em Engenharia Elétrica'
Formacaoacad.create! titulo: 'Bacharelado em Sistemas de Informação'
Formacaoacad.create! titulo: 'Bacharelado em Administração'
Formacaoacad.create! titulo: 'Bacharelado em Ciências Contábeis'
Formacaoacad.create! titulo: 'Bacharelado em Direito'
Formacaoacad.create! titulo: 'Bacharelado em Comunicação Social'
Formacaoacad.create! titulo: 'Bacharelado em Psicologia'
Formacaoacad.create! titulo: 'Bacharelado em Serviço Social'
Formacaoacad.create! titulo: 'Tecnológico em Radiologia'
Formacaoacad.create! titulo: 'Tecnológico em Gestão de Recursos Humanos'
Formacaoacad.create! titulo: 'Tecnológico em Logística'
Formacaoacad.create! titulo: 'Tecnológico em Segurança do Trabalho'
Formacaoacad.create! titulo: 'Tecnológico em Gastronomia'
Formacaoacad.create! titulo: 'Tecnológico em Redes de Computadores'
Formacaoacad.create! titulo: 'Tecnológico em Tecnologia da Informação'
Formacaoacad.create! titulo: 'Técnico em Eletrônica'
Formacaoacad.create! titulo: 'Técnico em Eletrotécnica'
Formacaoacad.create! titulo: 'Técnico em Informática'
Formacaoacad.create! titulo: 'Técnico em Mecânica'
Formacaoacad.create! titulo: 'Técnico em Mecatrônica'
Formacaoacad.create! titulo: 'Técnico em Refrigeração e Climatização'
Formacaoacad.create! titulo: 'Técnico em Administração'
Formacaoacad.create! titulo: 'Técnico em Edificações'
Formacaoacad.create! titulo: 'Técnico em Enfermagem'
Formacaoacad.create! titulo: 'Técnico em Geoprocessamento'
Formacaoacad.create! titulo: 'Técnico em Finanças'
Formacaoacad.create! titulo: 'Técnico em Prótese Dentária'
Formacaoacad.create! titulo: 'Técnico em Radiologia'
Formacaoacad.create! titulo: 'Técnico em Secretariado'
Formacaoacad.create! titulo: 'Técnico em Transporte de Cargas'
Formacaoacad.create! titulo: 'Técnico em Construção Civil'

Cargoocupado.create! titulo: 'Comandante de Pelotão'
Cargoocupado.create! titulo: 'Adjunto de Pelotão'
Cargoocupado.create! titulo: 'Comandante de Grupo de Combate'
Cargoocupado.create! titulo: 'Comandante de Esquadra'
Cargoocupado.create! titulo: 'Chefe de Almoxarifado'
Cargoocupado.create! titulo: 'Equipe de Almoxarifado'
Cargoocupado.create! titulo: 'Chefe de Garagem'
Cargoocupado.create! titulo: 'Equipe de Garagem'
Cargoocupado.create! titulo: 'Motorista'
Cargoocupado.create! titulo: 'Cozinheiro'
Cargoocupado.create! titulo: 'Chefe dos Serviços Gerais'
Cargoocupado.create! titulo: 'Equipe de Serviços Gerais'
Cargoocupado.create! titulo: 'Chefe de Seção de Aquisições Licitações e Contratos'
Cargoocupado.create! titulo: 'Equipe de Seção de Aquisições Licitações e Contratos'
Cargoocupado.create! titulo: 'Sargenteante de Companhia'
Cargoocupado.create! titulo: 'Furriel'
Cargoocupado.create! titulo: 'Chefe de Seção de TI'
Cargoocupado.create! titulo: 'Equipe de TI'
Cargoocupado.create! titulo: 'Chefe da Comunicação Social'
Cargoocupado.create! titulo: 'Equipe de Comunicação Social'
Cargoocupado.create! titulo: 'Chefe da 1ª Seção'
Cargoocupado.create! titulo: 'Equipe da 1ª Seção'
Cargoocupado.create! titulo: 'Chefe da 2ª Seção'
Cargoocupado.create! titulo: 'Equipe da 2ª Seção'
Cargoocupado.create! titulo: 'Chefe da 3ª Seção'
Cargoocupado.create! titulo: 'Equipe da 3ª Seção'
Cargoocupado.create! titulo: 'Chefe da 4ª Seção'
Cargoocupado.create! titulo: 'Equipe da 4ª Seção'
Cargoocupado.create! titulo: 'Equipe da Fiscalização Administrativa'
Cargoocupado.create! titulo: 'Protocolista'
Cargoocupado.create! titulo: 'Estafeta'
Cargoocupado.create! titulo: 'Equipe da Armaria'
Cargoocupado.create! titulo: 'Chefe de Oficina Mecânica'
Cargoocupado.create! titulo: 'Equipe de Oficina Mecânica'
Cargoocupado.create! titulo: 'Motorista de Embarcações'
Cargoocupado.create! titulo: 'Equipe de Embarcações'
Cargoocupado.create! titulo: 'Equipe de Saúde'
Cargoocupado.create! titulo: 'Equipe de Arquivo'
Cargoocupado.create! titulo: 'Equipe de Assessoria Jurídica'
Cargoocupado.create! titulo: 'Chefe da Assessoria Jurídica'
Cargoocupado.create! titulo: 'Chefe da Relações Públicas'
Cargoocupado.create! titulo: 'Equipe de Relações Públicas'
Cargoocupado.create! titulo: 'Equipe de Projetos de Engenharia'
Cargoocupado.create! titulo: 'Equipe Veterinária'

Certificacao.create! titulo: 'Cisco CCNA Routing & Switching'
Certificacao.create! titulo: 'Furukawa FCP Foundation'
Certificacao.create! titulo: 'Furukawa FCP Master'
Certificacao.create! titulo: 'Furukawa FCP FO'
